---
title: "how-to-calculate-and-plot-garnet-stoicheometry"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{how-to-calculate-and-plot-garnet-stoicheometry}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

#1. Libraries import

- install package devtools to download both ztR (for garnet steichieometry) and ggarnet to plot the garnet end-members in ternary diagram from github directly.
```{r setup}

#devtools::install_github("gabertol/ztR")
#devtools::install_github("gabertol/ggarnet")

library(tidyverse)
library(ztR)
library(ggarnet)
library(ggtern)


```

#2. DHZ calculation
```{r}

# Tourmaline
read.csv("./data/tourmaline_DHZ.csv") %>% 
  dplyr::select(specimen,sample=mineral,everything(),-X) %>% 
   bind_cols(.,chemical_formula(.,31,16))->tur

# Garnet
 read.csv("./data/garnet_DHZ.csv") %>% 
  dplyr::select(specimen,sample=mineral,everything(),-X) %>% 
   bind_cols(.,chemical_formula(.,24,16)) -> GT
  
# Epidote 
 read.csv("./data/epidote_DHZ.csv") %>% 
  dplyr::select(specimen,sample=mineral,everything(),-X) %>% 
    bind_cols(.,chemical_formula(.,c(12.5,13,12.5,12.5,12.5,13),8))  # vector with different qtty of oxigens
  


```


3. Plot in garnet classification ternary diagram

```{r}
ggarnet_fe_mn()+
geom_point(data=GT,aes(x=Fe3+Fe+Mn,z=Ca,y=Mg,shape=sample),size=4.5,alpha=0.5)

ggarnet_mn()+
geom_point(data=GT,aes(x=Fe3+Fe+Mn,y=Ca,z=Mg,,shape=sample),size=4.5,alpha=0.5)

ggarnet_tourmaline()+
  geom_point(data=tur,aes(x=Fe3+Fe,y=Al,z=Mg,shape=sample),size=4.5,alpha=0.5)
  
ggtern()+
  geom_point(data=tur,aes(x=Fe3+Fe,y=Ca,z=Mg,shape=sample),size=4.5,alpha=0.5)

```

# Crystallographic sites
```{r}
sites_epi<-tribble(~element,~prim_site,~sec_site,~total_site1,~total_site2,
                   "Si",1,1,3,3,
                   "Ti",2,2,3,3,
                   "Al",2,1,3,3, 
                   "Fe3",2,2,3,3, 
                   "Mn3",2,2,3,3,
                   "Y",3,3,2,2,  
                   "Ce",3,3,2,2, 
                   "La",3,3,2,2,  
                   "Fe",3,3,2,2,   
                   "Mn",3,3,2,2,  
                   "Mg",3,3,2,2,  
                   "Ca",3,3,2,2,  
                   "Na",3,3,2,2,   
                   "K",3,3,2,2,   
                   "OH",4,4,1,1)

sites_gar<-tribble(~element,~prim_site,~sec_site,~total_site1,~total_site2,~order_s1,~order_s2,
        "Si",1,1,6,6,1,1, 
        "Ti",2,2,4,4,NA,NA,
        "Al",2,1,4,6,1,2,  
        "Cr",2,2,4,4,NA,NA,  
        "Fe3",2,2,4,4,NA,NA,
        "Fe",3,3,6,6,NA,NA,  
        "Mn",3,3,6,6,NA,NA, 
        "Mg",3,3,6,6,NA,NA, 
        "Ca",3,3,6,6,NA,NA) 



sites_tur<-tribble(~element,~prim_site,~sec_site,~total_site1,~total_site2,~order_s1,~order_s2,
   "Si","T","T",6,6,1,1,
   "B","Z","T",6,6,1,3,
   "Al","Z","T",6,6,2,2,
   "Ti","Y","Y",3,3,NA,NA,
   "Fe","Y","Y",3,3,NA,NA,
   "Fe3","Z","Y",6,3,4,NA,
   "Mg","Z","Y",6,3,2,2,
   "Mn","Y","Y",3,3,NA,NA,
   "Zn","Y","Y",3,3,NA,NA,
   "Li","Y","Y",3,3,NA,NA,
   "K","X","X",1,1,NA,NA,
   "Ca","X","X",1,1,NA,NA,
   "Sr","X","X",1,1,NA,NA,
   "Na","X","X",1,1,NA,NA, 
   "F","W","W",4,4,2,2,   
   "OH","W","W",4,4,1,1,   
  
)
```


